Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Layout/MethodLength:
  Max: 40
Metrics/ParameterLists:
  Enabled: false
Documentation:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

# Disables:
Layout/SpaceInsideBlockBraces: 
  Enabled: false
Style/StringLiterals:
  Enabled: false