require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
  - 'sorbet/**'

Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/ParameterLists:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/SpaceInsideBlockBraces: 
  Enabled: false
Style/StringLiterals:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
